# Koyeb deployment configuration for LayerEdge with Scweet
services:
  # Main Next.js application
  - name: layeredge-app
    type: web
    instance_type: nano  # Start with smallest instance
    regions:
      - fra  # Frankfurt for EU users
    ports:
      - port: 3000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
      - key: SCWEET_SERVICE_URL
        value: http://scweet-service:8001
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
      - key: NEXTAUTH_URL
        value: ${NEXTAUTH_URL}
      - key: TWITTER_CLIENT_ID
        value: ${TWITTER_CLIENT_ID}
      - key: TWITTER_CLIENT_SECRET
        value: ${TWITTER_CLIENT_SECRET}
      - key: TWITTER_BEARER_TOKEN
        value: ${TWITTER_BEARER_TOKEN}
      - key: UPSTASH_REDIS_REST_URL
        value: ${UPSTASH_REDIS_REST_URL}
      - key: UPSTASH_REDIS_REST_TOKEN
        value: ${UPSTASH_REDIS_REST_TOKEN}
    build:
      type: docker
      dockerfile: Dockerfile
    health_check:
      http:
        path: /api/health
        port: 3000
    scaling:
      min: 1
      max: 3

  # Scweet scraping service
  - name: scweet-service
    type: worker
    instance_type: small  # Needs more resources for Chrome
    regions:
      - fra
    ports:
      - port: 8001
        protocol: http
    env:
      - key: REDIS_URL
        value: ${UPSTASH_REDIS_REST_URL}
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: DISPLAY
        value: :99
    build:
      type: docker
      dockerfile: Dockerfile.scweet
    health_check:
      http:
        path: /health
        port: 8001
    scaling:
      min: 1
      max: 2

# Global configuration
app:
  name: layeredge-community
  region: fra
