# Koyeb deployment configuration for LayerEdge with Scweet
services:
  # Main Next.js application
  - name: layeredge-app
    type: web
    instance_type: nano  # Start with smallest instance
    regions:
      - fra  # Frankfurt for EU users
    ports:
      - port: 3000
        protocol: http
    env:
      - key: NODE_ENV
        value: production
      # PRIORITY FIX: Scweet service URL for internal communication
      - key: SCWEET_SERVICE_URL
        value: http://scweet-service:8001
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
      - key: NEXTAUTH_URL
        value: ${NEXTAUTH_URL}
      # Twitter API (now fallback only)
      - key: TWITTER_CLIENT_ID
        value: ${TWITTER_CLIENT_ID}
      - key: TWITTER_CLIENT_SECRET
        value: ${TWITTER_CLIENT_SECRET}
      - key: TWITTER_BEARER_TOKEN
        value: ${TWITTER_BEARER_TOKEN}
      # Redis configuration
      - key: UPSTASH_REDIS_REST_URL
        value: ${UPSTASH_REDIS_REST_URL}
      - key: UPSTASH_REDIS_REST_TOKEN
        value: ${UPSTASH_REDIS_REST_TOKEN}
      # SECURITY: FUD Detection Configuration
      - key: FUD_DETECTION_ENABLED
        value: "true"
      - key: FUD_BLOCK_THRESHOLD
        value: "10"
      - key: FUD_WARN_THRESHOLD
        value: "4"
      - key: FUD_WHITELIST_ENABLED
        value: "true"
      - key: FUD_STRICT_MODE
        value: "false"
      # Community & Content Moderation
      - key: LAYEREDGE_COMMUNITY_URL
        value: ${LAYEREDGE_COMMUNITY_URL}
      # PRIORITY FIX: Playwright browser configuration
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /home/nextjs/.cache/ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
    build:
      type: docker
      dockerfile: Dockerfile
    health_check:
      http:
        path: /api/health
        port: 3000
    scaling:
      min: 1
      max: 3

  # Scweet scraping service
  - name: scweet-service
    type: worker
    instance_type: small  # Needs more resources for Chrome
    regions:
      - fra
    ports:
      - port: 8001
        protocol: http
    env:
      # PRIORITY FIX: Official Scweet v3.0+ configuration
      - key: REDIS_URL
        value: ${UPSTASH_REDIS_REST_URL}
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: DISPLAY
        value: :99
      - key: SCWEET_HEADLESS
        value: "true"
      - key: SCWEET_DISABLE_IMAGES
        value: "true"
      - key: SCWEET_CONCURRENCY
        value: "2"
    build:
      type: docker
      dockerfile: Dockerfile.scweet
    health_check:
      http:
        path: /health
        port: 8001
    scaling:
      min: 1
      max: 2

# Global configuration
app:
  name: layeredge-community
  region: fra
